### ISSUE TITLE
QGEP plugin doesn't handle custom QGIS profile location path

### ISSUE THREAD

**Issue by haubourg** [QGEP/qgepplugin#15]
using QGIS 2.18 ltr, I have a custom QGIS profile in `F:\APPS\QGIS_PROFILES\qgep\.qgis2`

I modified qgis-ltr.bat like this to have my QGEP dedicated profile used:
`start "QGIS" /B "%OSGEO4W_ROOT%"\bin\qgis-ltr-dev-bin.exe --configpath "F:\APPS\QGIS_PROFILES\qgep\.qgis2" %*`

Then I built QGIS plugin in my linux machine and  deployed the  QGIS plugin into `F:\APPS\QGIS_PROFILES\qgep\.qgis2\python\plugins\qgepplugin`

When lauching QGIS, it seems that the handling of the log file is not handled correctly as it tries to use a default profile location in `C:\\home\\regis\\APPS\\..` not the actual profile path. 

```
Impossible de charger l'extension qgepplugin provoque une erreur lors de l'appel de sa méthode classFactory() 

IOError: [Errno 2] No such file or directory: u'C:\\home\\regis\\APPS\\QGIS_PROFILES\\qgep\\log_qgep_plugin.log' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-ltr-dev/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "F:\APPS\QGIS_PROFILES\qgep\.qgis2/python/plugins\qgepplugin\__init__.py", line 31, in classFactory
    return QgepPlugin(iface)
  File "F:\APPS\QGIS_PROFILES\qgep\.qgis2/python/plugins\qgepplugin\qgepplugin.py", line 98, in __init__
    self.initLogger()
  File "F:\APPS\QGIS_PROFILES\qgep\.qgis2/python/plugins\qgepplugin\qgepplugin.py", line 129, in initLogger
    log_handler = logging.FileHandler(logfile)
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 902, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 925, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: u'C:\\home\\regis\\APPS\\QGIS_PROFILES\\qgep\\log_qgep_plugin.log'
```

any idea of what's happening here?

**Comment by m-kuhn** [comment]
Probably a leftover of a configuration of a previous installation.

Anyway, exceptions like this shouldn't prevent the plugin from working.

How do we deal with fixing smaller issues like this? Go via an offer?

**Comment by haubourg** [comment]
Hi Matthias, 
another point, the log file is created correctly. 
I just filed this for the record, I have no customer demand here, it might be a corner case for most users. 
@ponceta are you concerned by custom 'configpath' option in your QGIS deploy?

**Comment by haubourg** [comment]
@m-kuhn Can you roughly estimate the task so that we choose either helpdesk or a formal offer ?

**Comment by m-kuhn** [comment]
1 hour to avoid this particular error, in case there are no follow up issues.

**Comment by sjib** [comment]
@haubourg Is this solved with https://github.com/QGEP/qgepplugin/releases 1.18?

**Comment by sjib** [comment]
@haubourg I close this, please reopen if necessary.
