### ISSUE TITLE
plugin releases have a version=dev tag in metadata.txt

### ISSUE THREAD

**Issue by haubourg** [QGEP/qgepplugin#16]
It should be replaced by the tag number when creating the release.

**Comment by 3nids** [comment]
you can use our own repo to download the plugin
https://raw.githubusercontent.com/QGEP/repository/master/plugins.xml

in there the releases are correctly made with a proper version

**Comment by haubourg** [comment]
oh OK, that's a bit confusing but not a big deal
Thanks
