### ISSUE TITLE
qgepplugin processing crash/errors

### ISSUE THREAD

**Issue by max-trolliet** [QGEP/qgepplugin#19]
Related to #81 and #380 

I still have issues with the processings. 
 
For Snap reach geometry : the Crash is still there.

For the change direction, I don't have a crash (yet) but this message : 
---
Processing algorithm…
Démarrage de l'algorithme 'Change reaches direction'…
Paramètres en entrée:
{ 'REACH_LAYER' : 'service=\'pg_qgep\' key=\'obj_id\' srid=2056 type=CompoundCurveZ table=\"qgep_od\".\"vw_qgep_reach\" (progression_geometry) sql=' }

Traceback (most recent call last):
File "C:/Users/mtt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\processing_provider\change_reach_direction.py", line 98, in processAlgorithm transaction.executeSql('SELECT qgep_od.reach_direction_change(\'{{{obj_ids}}}\');'.format(obj_ids=','.join(selected_obj_ids)))
AttributeError: 'NoneType' object has no attribute 'executeSql'

Échec d'exécution au bout de 0.03 secondes

Chargement des couches de résultat
Algorithme 'Change reaches direction' terminé
---

**Comment by m-kuhn** [comment]
@max-trolliet can you set the layer into edit mode and run again?

The issue here is a different one than before. Originally we really had a crash (i.e. QGIS was dead, Oops - Window), now we are left with an error (QGIS continues running, it's just the operation that did not work).

**Comment by max-trolliet** [comment]
@m-kuhn  I already tried it with the layer in edit mode. I get the same error message.

**Comment by max-trolliet** [comment]
You mean this : 

![image](https://user-images.githubusercontent.com/13679128/44251289-1c168780-a1f8-11e8-88ed-05d3549252af.png)

I tried to toggle it on and off. I still get the same error message.

**Comment by m-kuhn** [comment]
Can you test with the original qgep demo project?

**Comment by max-trolliet** [comment]
I'm using the project downloaded from github yesterday, but with Prilly data... Is it enough?

**Comment by m-kuhn** [comment]
What's the version of the plugin?

**Comment by max-trolliet** [comment]
I freashly reinstalled everything yesterday in order to check the processing 

qgis : https://github.com/qgis/QGIS/commit/69201021d5 

qgep plufggin : 1.1.2

**Comment by m-kuhn** [comment]
Can you open a separate new issue for snapping with the contents from the oops dialog?

**Comment by m-kuhn** [comment]
`iface.activeLayer().dataProvider()

**Comment by m-kuhn** [comment]
Discussion continued in #21
