### ISSUE TITLE
Creation of a wastewater structure does not trigger the form

### ISSUE THREAD

**Issue by ponceta** [QGEP/qgepplugin#2]
Using the plugin, starting data entry activates the edition on the wastewater structures

![image](https://cloud.githubusercontent.com/assets/8614223/24752576/c6f81cd4-1ace-11e7-8d71-85c7baa18d78.png)

Add a waste waterstructure

Form does not pop up.

Stop data entry will fail since no attributes have been supplied for ws type.

Adding a reach will succeed since the form pops up correctly (and no attribute is forced).

I thought of plugin missbehaviour from plugin but it's maybe not that.

**Comment by m-kuhn** [comment]
Does it work if you just use the add feature tool on vw_qgep_wastewater_structure? (i.e. without the data entry tool).

**Comment by ponceta** [comment]
No :) That's why I'm not sure :)

**Comment by m-kuhn** [comment]
Can you check in layer properties -> fields, bottom right "suppress feature form"

**Comment by ponceta** [comment]
Fixed.
