### ISSUE TITLE
Snap Reach Geometry - crash report

### ISSUE THREAD

**Issue by max-trolliet** [QGEP/qgepplugin#20]
Here is the crash report for the snap reach : 

h2. User Feedback

h2. Report Details

*Crash ID*: 7ee3d1bc24f4a4372516c66006203bec50a85b38

*Stack Trace*
<pre>
QgsRasterMinMaxOrigin::limitsString :
QgsRasterMinMaxOrigin::limitsString :
QgsRasterMinMaxOrigin::limitsString :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Check_offset_exclusive :
std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Check_offset_exclusive :
PyFrame_New :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_sip :
PyInit__gui :
PyInit__gui :
QgsRendererPropertiesDialog::~QgsRendererPropertiesDialog :
QgsRendererPropertiesDialog::~QgsRendererPropertiesDialog :
QgsRendererPropertiesDialog::~QgsRendererPropertiesDialog :
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRasterMinMaxOrigin::limitsString :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRasterMinMaxOrigin::limitsString :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
PyInit__gui :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRasterMinMaxOrigin::limitsString :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRasterMinMaxOrigin::limitsString :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgisApp::qt_metacast :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.3.0-Master
QGIS code revision: commit:69201021d5
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by m-kuhn** [comment]
Is the `qgis-dev-pdb` package installed?

**Comment by max-trolliet** [comment]
Where can I check that? In the OSGeo installer?

**Comment by m-kuhn** [comment]
Yes

**Comment by max-trolliet** [comment]
I have the 3.3.0-43 installed.

**Comment by m-kuhn** [comment]
of qgis-dev and qgis-dev-pdb?

**Comment by max-trolliet** [comment]
![image](https://user-images.githubusercontent.com/13679128/44255490-90f0be00-a206-11e8-902d-a4501cc1d574.png)

**Comment by max-trolliet** [comment]
Ah! better! 

No crash, but error message : 

Une erreur est survenue lors de l'éxécution du code Python: 

NotImplementedError: QgsProcessingAlgorithm.createInstance() is abstract and must be overridden 
NotImplementedError: QgsProcessingAlgorithm.createInstance() is abstract and must be overridden


Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.3.0-Master Master, 69201021d5 

Chemin Python :
C:/OSGEO4~1/apps/qgis-dev/./python
C:/Users/mtt/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/mtt/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis-dev/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGEO4~1\apps\Python36\DLLs
C:\OSGEO4~1\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python36
C:\OSGEO4~1\apps\Python36\lib\site-packages
C:/Users/mtt/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/05. Integration/01. TRX/01. PGEE/qgep/070818_new_schema

**Comment by max-trolliet** [comment]
Still have this crash : 

Crash ID: 180136bb0c12777afe876ce6d9db458957a56e45


Stack Trace


QgsRasterMinMaxOrigin::limitsString :
QgsRasterMinMaxOrigin::limitsString :
QgsRasterMinMaxOrigin::limitsString :
std::basic_string,std::allocator >::_Check_offset_exclusive :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyErr_Occurred :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_sip :
PyInit__gui :
PyInit__gui :
QgsRendererPropertiesDialog::~QgsRendererPropertiesDialog :
QgsRendererPropertiesDialog::~QgsRendererPropertiesDialog :
QgsRendererPropertiesDialog::~QgsRendererPropertiesDialog :
QMetaObject::activate :
QDialogButtonBox::~QDialogButtonBox :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRasterMinMaxOrigin::limitsString :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRasterMinMaxOrigin::limitsString :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyCFunction_FastCallDict :
PyObject_GenericGetAttr :
PyEval_EvalFrameDefault :
PyFunction_FastCallDict :
PyObject_CallFunctionObjArgs :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
PyInit__gui :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRasterMinMaxOrigin::limitsString :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsRasterMinMaxOrigin::limitsString :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgisApp::qt_metacast :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.3.0-Master
QGIS code revision: 69201021d5
Compiled against Qt: 5.9.2
Running against Qt: 5.9.2
Compiled against GDAL: 2.2.4
Running against GDAL: 2.2.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

**Comment by sjib** [comment]
@max-trolliet is this still an issue with the latest version?

**Comment by sjib** [comment]
@max-trolliet I close this - please reopen if necessary.
