### ISSUE TITLE
Change reach direction can't save in base

### ISSUE THREAD

**Issue by max-trolliet** [QGEP/qgepplugin#24]
With the 1.1.3 plugin version, the tool to change reaches direction is working well. The down part is that it is not yet possible to save the changes. 

One has to create another action on the dB in order for QGIS to toogle the save button on. If this is not done, when leaving the edition mode, the changes are not saved.

**Comment by sjib** [comment]
@max-trolliet Is this still an issue with the latest version (1.18)

**Comment by urskaufmann** [comment]
Yes, it works!

**Comment by sjib** [comment]
@max-trolliet Please test also and then close if ok
