### ISSUE TITLE
Error with refresh topology

### ISSUE THREAD

**Issue by varrieta** [QGEP/qgepplugin#29]
![capture](https://user-images.githubusercontent.com/20111558/47911717-7be70b00-de96-11e8-95c6-b4a3314354a1.PNG)

**Comment by m-kuhn** [comment]
Still using QGIS 2?

**Comment by m-kuhn** [comment]
That's not the issue actually, but there might be others...

**Comment by m-kuhn** [comment]
What do you have in the QGEP settings?

![image](https://user-images.githubusercontent.com/588407/47912620-9ec6ee80-de99-11e8-9ff4-fe05f2864255.png)

**Comment by varrieta** [comment]
Yes still using QGIS 2 for QGEP ^^

![capture](https://user-images.githubusercontent.com/20111558/47915400-13525b00-dea3-11e8-945d-9fa5ac2463c7.PNG)

Okay I really have to get back on track, didn't even know there were settings with the plugins..

With the settings, it does work.. My bad

**Comment by m-kuhn** [comment]
That's mostly a leftover. New code tries to search within the loaded layers.
E.g. for connect network elements you do not need to configure input layers anymore.
It would be nice to do the same here.

**Comment by varrieta** [comment]
Actually we didn't have this problem before and the project didn't change.. Strange.

Indeed would be nice to have it!

**Comment by sjib** [comment]
@varrieta Is this still an issue and worth investing any effort? Then please assign m-kuhn

**Comment by sjib** [comment]
I close it, please reopen if necessary.
