### ISSUE TITLE
Latest release tag in github by default on 0.5.11

### ISSUE THREAD

**Issue by haubourg** [QGEP/qgepplugin#4]
Hi Matthias, 
nothing urgent or important: 
in github, the latest release tag is fixed to 0.5.11 when there are newer tags. 
This can be confusing for a user landing here to pick the plugin. 

![image](https://user-images.githubusercontent.com/1629853/28460235-75e7c02e-6e11-11e7-9e18-88a8bd16a1f2.png)

I suppose this is due to the automatic release process.

**Comment by ponceta** [comment]
0.6.6 is 0.5.11? a bit confusing yes.

**Comment by sjib** [comment]
It still shows v0.5.11 as latest relase, but there are many newer ones
https://github.com/QGEP/qgepplugin/releases

**Comment by sjib** [comment]
Latest release has to be set manually
