### ISSUE TITLE
Update qgep plugin error : "cannot import name release"

### ISSUE THREAD

**Issue by ponceta** [QGEP/qgepplugin#8]
On Win x64, QGIS 2.18.16

Linked to networkx

![image](https://user-images.githubusercontent.com/8614223/35793675-ef5bf410-0a52-11e8-9f1d-1616cb43ca72.png)

![image](https://user-images.githubusercontent.com/8614223/35794059-762ede16-0a54-11e8-8be8-b5929dc3e2c1.png)

**Comment by lbartoletti** [comment]
Solution from ML works:
via OSGeo4W install networkx and setuptools

I noticed only a problem with users having a non-ascii login like me: "Loïc"... but it's my bad... python2 and windows :)

**Comment by kandre** [comment]
OSGeo4W install networkx and setuptools it solved the problem for me, thanks

**Comment by m-kuhn** [comment]
Should be fixed with the next release (QGS 2.18.20) and new OSGeo4W installs.

https://lists.osgeo.org/pipermail/qgis-psc/2018-June/006252.html

Please reopen if you can reproduce this problem with a fresh installation.
